version: '2'
services:
  recipeme-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/RecipeMe/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=RecipeMe
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
